# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Confix

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
       
        python -m pip install wheel
        
        python -m pip install rpm alien 
        
        
 
    - name: Create package
      run: |      
        man alien
        whereis alien
        /usr/bin/alien      
        
        ls -lR /usr/bin > lsdebian.txt
        
        
    - name: builds 1
      uses: actions/upload-artifact@v2
      with:
        name: builds1
        path: dist
     
    - name: deb 
      uses: actions/upload-artifact@v2      
      with:
        name: deb 
        path: lsdebian.txt
        